### ISSUE TITLE
Nothing happens when setMaxCount is set to 1

### ISSUE THREAD

**Issue by marconealberto** [DroidNinja/Android-FilePicker#113] opened 2017-11-08 15:28 UTC
The Activity is not launched, and the problem goes away if I set it to a different number.

**Comment by Alb93** [comment] 2017-11-09 17:23
Also for me: new activity starts and immediately closes without any stack trace or log.

My code: `String[] pdfTypes = {".pdf"};
        String[] txtTypes = {".txt"};
        String[] wordTypes = {".doc", ".word"};
        FilePickerBuilder.getInstance().setMaxCount(1)
                .enableDocSupport(false)
                .addFileSupport("TXT",txtTypes, R.drawable.txt)
                .addFileSupport("PDF",pdfTypes, R.drawable.pdf)
                .addFileSupport("WORD",wordTypes, R.drawable.word)
                .setActivityTheme(R.style.AppTheme)
                .pickFile(this);`

Please fix :)

**Comment by zackpollard** [comment] 2017-11-10 21:00
I am also experiencing this behaviour, it fails whenever setMaxCount is 1.

**Comment by DroidNinja** [comment] 2017-11-11 11:57
Thanks for reporting. Fixed in 2.1.0

**Comment by RuslanKham322** [comment] 2017-11-13 07:45
Same problem with media picking.
`MediaDetailsActivity`:
`onCreateOptionsMenu` calls `onItemSelected()`. In this method:
```java
...
if(maxCount==1) {
    setResult(RESULT_OK, null);
    finish();
}
...
```

**Comment by mrgames13** [comment] 2017-11-15 18:30
I also ran into this problem. App crashes when clicking on one folder.

**Comment by ipodib** [comment] 2017-11-18 15:57
The issue is not fixed in 2.1.0.  I see the same problem. And according to @RuslanKham322 reason is simple: library returns nothing when maxCount is 1.

**Comment by forming** [comment] 2017-11-19 18:17
The issue still present.

**Comment by CallumCoombes** [comment] 2017-11-19 19:28
Yeah, this is still an issue. Not crashing, just cannot enter folders containing images making it unusable.

**Comment by ipodib** [comment] 2017-11-20 02:18
Everyone who needs a workaround for this bug can revert to 2.0.8 version. This version does not have this bug.

**Comment by CallumCoombes** [comment] 2017-11-20 10:03
Tested reverting to 2.0.8 and you are correct.

**Comment by DroidNinja** [comment] 2017-11-20 13:30
Hey g

**Comment by DroidNinja** [comment] 2017-11-20 13:32
Hey guys could you verify if its fixed ? Last version was really a mess. Sorry :/

**Comment by forming** [comment] 2017-11-20 13:59
Just checked and it seems to be working on 2.1.1 version. Thanks!

**Closed** 2017-11-20 18:43 UTC
